RDbItems.enchant = {
	{7411, "Enchanting", "附魔"},
	{7412, "Enchanting", "附魔"},
	{7413, "Enchanting", "附魔"},
	{7418, "Enchant Bracer - Minor Health", "附魔护腕 - 初级生命"},
	{7420, "Enchant Chest - Minor Health", "附魔胸甲 - 初级生命"},
	{7421, "Runed Copper Rod", "符文铜棒"},
	{7426, "Enchant Chest - Minor Absorption", "附魔胸甲 - 初级吸收"},
	{7428, "Enchant Bracer - Minor Deflect", "附魔护腕 - 初级躲闪"},
	{7443, "Enchant Chest - Minor Mana", "附魔胸甲 - 初级法力"},
	{7454, "Enchant Cloak - Minor Resistance", "附魔披风 - 初级抗性"},
	{7457, "Enchant Bracer - Minor Stamina", "附魔护腕 - 初级耐力"},
	{7745, "Enchant 2H Weapon - Minor Impact", "附魔双手武器 - 初级冲击"},
	{7748, "Enchant Chest - Lesser Health", "附魔胸甲 - 次级生命"},
	{7766, "Enchant Bracer - Minor Spirit", "附魔护腕 - 初级精神"},
	{7771, "Enchant Cloak - Minor Protection", "附魔披风 - 初级防护"},
	{7776, "Enchant Chest - Lesser Mana", "附魔胸甲 - 次级法力"},
	{7779, "Enchant Bracer - Minor Agility", "附魔护腕 - 初级敏捷"},
	{7782, "Enchant Bracer - Minor Strength", "附魔护腕 - 初级力量"},
	{7786, "Enchant Weapon - Minor Beastslayer", "附魔武器 - 初级屠兽"},
	{7788, "Enchant Weapon - Minor Striking", "附魔武器 - 初级打击"},
	{7793, "Enchant 2H Weapon - Lesser Intellect", "附魔双手武器 - 次级智力"},
	{7795, "Runed Silver Rod", "符文银棒"},
	{7857, "Enchant Chest - Health", "附魔胸甲 - 生命"},
	{7859, "Enchant Bracer - Lesser Spirit", "附魔护腕 - 次级精神"},
	{7861, "Enchant Cloak - Lesser Fire Resistance", "附魔披风 - 次级火焰抗性"},
	{7863, "Enchant Boots - Minor Stamina", "附魔靴子 - 初级耐力"},
	{7867, "Enchant Boots - Minor Agility", "附魔靴子 - 初级敏捷"},
	{13262, "Disenchant", "分解"},
	{13378, "Enchant Shield - Minor Stamina", "附魔盾牌 - 初级耐力"},
	{13380, "Enchant 2H Weapon - Lesser Spirit", "附魔双手武器 - 次级精神"},
	{13419, "Enchant Cloak - Minor Agility", "附魔披风 - 初级敏捷"},
	{13421, "Enchant Cloak - Lesser Protection", "附魔披风 - 次级防护"},
	{13464, "Enchant Shield - Lesser Protection", "附魔盾牌 - 次级防护"},
	{13485, "Enchant Shield - Lesser Spirit", "附魔盾牌 - 次级精神"},
	{13501, "Enchant Bracer - Lesser Stamina", "附魔护腕 - 次级耐力"},
	{13503, "Enchant Weapon - Lesser Striking", "附魔武器 - 次级打击"},
	{13522, "Enchant Cloak - Lesser Shadow Resistance", "附魔披风 - 次级暗影抗性"},
	{13529, "Enchant 2H Weapon - Lesser Impact", "附魔双手武器 - 次级冲击"},
	{13536, "Enchant Bracer - Lesser Strength", "附魔护腕 - 次级力量"},
	{13538, "Enchant Chest - Lesser Absorption", "附魔胸甲 - 次级吸收"},
	{13607, "Enchant Chest - Mana", "附魔胸甲 - 法力"},
	{13612, "Enchant Gloves - Mining", "附魔手套 - 采矿"},
	{13617, "Enchant Gloves - Herbalism", "附魔手套 - 草药学"},
	{13620, "Enchant Gloves - Fishing", "附魔手套 - 钓鱼"},
	{13622, "Enchant Bracer - Lesser Intellect", "附魔护腕 - 次级智力"},
	{13626, "Enchant Chest - Minor Stats", "附魔胸甲 - 初级属性"},
	{13628, "Runed Golden Rod", "符文金棒"},
	{13631, "Enchant Shield - Lesser Stamina", "附魔盾牌 - 次级耐力"},
	{13635, "Enchant Cloak - Defense", "附魔披风 - 防御"},
	{13637, "Enchant Boots - Lesser Agility", "附魔靴子 - 次级敏捷"},
	{13640, "Enchant Chest - Greater Health", "附魔胸甲 - 强效生命"},
	{13642, "Enchant Bracer - Spirit", "附魔护腕 - 精神"},
	{13644, "Enchant Boots - Lesser Stamina", "附魔靴子 - 次级耐力"},
	{13646, "Enchant Bracer - Lesser Deflection", "附魔护腕 - 次级躲闪"},
	{13648, "Enchant Bracer - Stamina", "附魔护腕 - 耐力"},
	{13653, "Enchant Weapon - Lesser Beastslayer", "附魔武器 - 次级屠兽"},
	{13655, "Enchant Weapon - Lesser Elemental Slayer", "附魔武器 - 次级元素杀手"},
	{13657, "Enchant Cloak - Fire Resistance", "附魔披风 - 火焰抗性"},
	{13659, "Enchant Shield - Spirit", "附魔盾牌 - 精神"},
	{13661, "Enchant Bracer - Strength", "附魔护腕 - 力量"},
	{13663, "Enchant Chest - Greater Mana", "附魔胸甲 - 强效法力"},
	{13687, "Enchant Boots - Lesser Spirit", "附魔靴子 - 次级精神"},
	{13689, "Enchant Shield - Lesser Block", "附魔盾牌 - 次级招架"},
	{13693, "Enchant Weapon - Striking", "附魔武器 - 打击"},
	{13695, "Enchant 2H Weapon - Impact", "附魔双手武器 - 冲击"},
	{13698, "Enchant Gloves - Skinning", "附魔手套 - 剥皮"},
	{13700, "Enchant Chest - Lesser Stats", "附魔胸甲 - 次级属性"},
	{13702, "Runed Truesilver Rod", "符文真银棒"},
	{13746, "Enchant Cloak - Greater Defense", "附魔披风 - 强效防御"},
	{13794, "Enchant Cloak - Resistance", "附魔披风 - 抗性"},
	{13815, "Enchant Gloves - Agility", "附魔手套 - 敏捷"},
	{13817, "Enchant Shield - Stamina", "附魔盾牌 - 耐力"},
	{13822, "Enchant Bracer - Intellect", "附魔护腕 - 智力"},
	{13836, "Enchant Boots - Stamina", "附魔靴子 - 耐力"},
	{13841, "Enchant Gloves - Advanced Mining", "附魔手套 - 高级采矿"},
	{13846, "Enchant Bracer - Greater Spirit", "附魔护腕 - 强效精神"},
	{13858, "Enchant Chest - Superior Health", "附魔胸甲 - 超强生命"},
	{13868, "Enchant Gloves - Advanced Herbalism", "附魔手套 - 高级草药学"},
	{13882, "Enchant Cloak - Lesser Agility", "附魔披风 - 次级敏捷"},
	{13887, "Enchant Gloves - Strength", "附魔手套 - 力量"},
	{13890, "Enchant Boots - Minor Speed", "附魔靴子 - 初级速度"},
	{13898, "Enchant Weapon - Fiery Weapon", "附魔武器 - 烈焰武器"},
	{13905, "Enchant Shield - Greater Spirit", "附魔盾牌 - 强效精神"},
	{13915, "Enchant Weapon - Demonslaying", "附魔武器 - 屠魔"},
	{13917, "Enchant Chest - Superior Mana", "附魔胸甲 - 超强法力"},
	{13920, "Enchanting", "附魔"},
	{13931, "Enchant Bracer - Deflection", "附魔护腕 - 躲闪"},
	{13933, "Enchant Shield - Frost Resistance", "附魔盾牌 - 冰霜抗性"},
	{13935, "Enchant Boots - Agility", "附魔靴子 - 敏捷"},
	{13937, "Enchant 2H Weapon - Greater Impact", "附魔双手武器 - 强效冲击"},
	{13939, "Enchant Bracer - Greater Strength", "附魔护腕 - 强效力量"},
	{13941, "Enchant Chest - Stats", "附魔胸甲 - 属性"},
	{13943, "Enchant Weapon - Greater Striking", "附魔武器 - 强效打击"},
	{13945, "Enchant Bracer - Greater Stamina", "附魔护腕 - 强效耐力"},
	{13947, "Enchant Gloves - Riding Skill", "附魔手套 - 骑术"},
	{13948, "Enchant Gloves - Minor Haste", "附魔手套 - 初级急速"},
	{14293, "Lesser Magic Wand", "次级魔法杖"},
	{14807, "Greater Magic Wand", "强效魔法杖"},
	{14809, "Lesser Mystic Wand", "次级秘法魔杖"},
	{14810, "Greater Mystic Wand", "强效秘法杖"},
	{15596, "Smoking Heart of the Mountain", "浓烟山脉之心"},
	{17180, "Enchanted Thorium", "魔化瑟银锭"},
	{17181, "Enchanted Leather", "魔化皮"},
	{20008, "Enchant Bracer - Greater Intellect", "附魔护腕 - 强效智力"},
	{20009, "Enchant Bracer - Superior Spirit", "附魔护腕 - 超强精神"},
	{20010, "Enchant Bracer - Superior Strength", "附魔护腕 - 超强力量"},
	{20011, "Enchant Bracer - Superior Stamina", "附魔护腕 - 超强耐力"},
	{20012, "Enchant Gloves - Greater Agility", "附魔手套 - 强效敏捷"},
	{20013, "Enchant Gloves - Greater Strength", "附魔手套 - 强效力量"},
	{20014, "Enchant Cloak - Greater Resistance", "附魔披风 - 强效抗性"},
	{20015, "Enchant Cloak - Superior Defense", "附魔披风 - 超强防御"},
	{20016, "Enchant Shield - Superior Spirit", "附魔盾牌 - 活力"},
	{20017, "Enchant Shield - Greater Stamina", "附魔盾牌 - 强效耐力"},
	{20020, "Enchant Boots - Greater Stamina", "附魔靴子 - 强效耐力"},
	{20023, "Enchant Boots - Greater Agility", "附魔靴子 - 强效敏捷"},
	{20024, "Enchant Boots - Spirit", "附魔靴子 - 精神"},
	{20025, "Enchant Chest - Greater Stats", "附魔胸甲 - 强效属性"},
	{20026, "Enchant Chest - Major Health", "附魔胸甲 - 特效生命"},
	{20028, "Enchant Chest - Major Mana", "附魔胸甲 - 特效法力"},
	{20029, "Enchant Weapon - Icy Chill", "附魔武器 - 冰寒"},
	{20030, "Enchant 2H Weapon - Superior Impact", "附魔双手武器 - 超强冲击"},
	{20031, "Enchant Weapon - Superior Striking", "附魔武器 - 超强打击"},
	{20032, "Enchant Weapon - Lifestealing", "附魔武器 - 生命偷取"},
	{20033, "Enchant Weapon - Unholy Weapon", "附魔武器 - 邪恶武器"},
	{20034, "Enchant Weapon - Crusader", "附魔武器 - 十字军"},
	{20035, "Enchant 2H Weapon - Major Spirit", "附魔双手武器 - 特效精神"},
	{20036, "Enchant 2H Weapon - Major Intellect", "附魔双手武器 - 特效智力"},
	{20051, "Runed Arcanite Rod", "符文奥金棒"},
	{21931, "Enchant Weapon - Winter's Might", "附魔武器 - 寒冬之力"},
	{22749, "Enchant  Weapon - Spell Power", "法术能量"},
	{22750, "Enchant  Weapon - Healing Power", "治疗能量"},
	{23799, "Enchant Weapon - Strength", "附魔武器 - 力量"},
	{23800, "Enchant Weapon - Agility", "附魔武器 - 敏捷"},
	{23801, "Enchant Bracer - Mana Regeneration", "附魔护腕 - 法力回复"},
	{23802, "Enchant Bracer - Healing Power", "附魔护腕 - 治疗能力"},
	{23803, "Enchant Weapon - Mighty Spirit", "附魔武器 - 极效精神"},
	{23804, "Enchant Weapon - Mighty Intellect", "附魔武器 - 极效智力"},
	{25072, "Enchant Gloves - Threat", "附魔手套 - 威胁"},
	{25073, "Enchant Gloves - Shadow Power", "附魔手套 - 暗影能量"},
	{25074, "Enchant Gloves - Frost Power", "附魔手套 - 冰霜能量"},
	{25078, "Enchant Gloves - Fire Power", "附魔手套 - 火焰能量"},
	{25079, "Enchant Gloves - Healing Power", "附魔手套 - 治疗能量"},
	{25080, "Enchant Gloves - Superior Agility", "附魔手套 - 超强敏捷"},
	{25081, "Enchant Cloak - Greater Fire Resistance", "附魔披风 - 强效火焰抗性"},
	{25082, "Enchant Cloak - Greater Nature Resistance", "附魔披风 - 强效自然抗性"},
	{25083, "Enchant Cloak - Stealth", "附魔披风 - 潜行"},
	{25084, "Enchant Cloak - Subtlety", "附魔披风 - 狡诈"},
	{25086, "Enchant Cloak - Dodge", "附魔披风 - 躲闪"},
	{25124, "Minor Wizard Oil", "初级巫师之油"},
	{25125, "Minor Mana Oil", "初级法力之油"},
	{25126, "Lesser Wizard Oil", "次级巫师之油"},
	{25127, "Lesser Mana Oil", "次级法力之油"},
	{25128, "Wizard Oil", "巫师之油"},
	{25129, "Brilliant Wizard Oil", "卓越巫师之油"},
	{25130, "Brilliant Mana Oil", "卓越法力之油"},
	{27837, "Enchant 2H Weapon - Agility", "附魔双手武器 - 敏捷"},
}
